Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,17 +21,6 @@ jobs:
       with:
         version: '1.10'
 
-    - name: Cache Julia packages
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.julia/compiled
-          ~/.julia/artifacts
-          ~/.julia/packages
-        key: julia-cache-${{ hashFiles('colorResources/**/Project.toml', 'colorResources/**/Manifest.toml') }}
-        restore-keys: |
-          julia-cache-
-
     - name: Install Julia packages
       run: |
         julia -e '
@@ -49,19 +38,11 @@ jobs:
       with:
         python-version: '3.11'
 
-    - name: Cache Python packages
-      uses: actions/cache@v3
-      with:
-        path: ~/.cache/pip
-        key: python-cache-${{ hashFiles('colorResources/requirements.txt') }}
-        restore-keys: |
-          python-cache-
-
     - name: Install Python packages
       run: |
         python -m pip install --upgrade pip
-        pip install -r colorResources/requirements.txt || { echo "Error installing Python packages"; exit 1; }
+        pip install numpy matplotlib juliacall || { echo "Error installing Python packages"; exit 1; }
 
     - name: Run Python script
       run: |
-        python colorResources/test_consistency.py || { echo "Error running Python script"; exit 1; }
+        python test_consistency.py || { echo "Error running Python script"; exit 1; }
